version: "2"

linters:
  default: standard

formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
      custom-order: true
    gofumpt:
      extra:
        group-params: true
        clothe-returns: true
        balance-calls: true
