package abnf_gen_test

import (
	"bytes"
	"os"
	"testing"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	"github.com/ghettovoice/abnf/pkg/abnf_gen"
)

var _ = Describe("CodeGenerator", func() {
	DescribeTable("",
		func(abnfPath, expPath string, gen *abnf_gen.CodeGenerator) {
			raw, err := os.ReadFile(abnfPath)
			Expect(err).ShouldNot(HaveOccurred())

			src := bytes.NewBuffer(raw)
			Expect(gen.ReadFrom(src)).Error().ShouldNot(HaveOccurred())

			var dst bytes.Buffer
			Expect(gen.WriteTo(&dst)).Error().ShouldNot(HaveOccurred())

			exp, err := os.ReadFile(expPath)
			Expect(err).ShouldNot(HaveOccurred())

			Expect(dst.String()).Should(Equal(string(exp)))
		},
		Entry("rules.abnf",
			"../abnf_core/rules.abnf",
			"../abnf_core/rules.go",
			&abnf_gen.CodeGenerator{
				PackageName: "abnf_core",
				AsOperators: true,
			},
		),
		Entry("rules.abnf",
			"../abnf_def/rules.abnf",
			"../abnf_def/rules.go",
			&abnf_gen.CodeGenerator{
				PackageName: "abnf_def",
				AsOperators: true,
				External: map[string]abnf_gen.ExternalRule{
					"CRLF": {
						PackagePath: "github.com/ghettovoice/abnf/pkg/abnf_core",
						PackageName: "abnf_core",
						IsOperator:  true,
					},
					"WSP": {
						PackagePath: "github.com/ghettovoice/abnf/pkg/abnf_core",
						PackageName: "abnf_core",
						IsOperator:  true,
					},
					"BIT": {
						PackagePath: "github.com/ghettovoice/abnf/pkg/abnf_core",
						PackageName: "abnf_core",
						IsOperator:  true,
					},
					"VCHAR": {
						PackagePath: "github.com/ghettovoice/abnf/pkg/abnf_core",
						PackageName: "abnf_core",
						IsOperator:  true,
					},
					"DIGIT": {
						PackagePath: "github.com/ghettovoice/abnf/pkg/abnf_core",
						PackageName: "abnf_core",
						IsOperator:  true,
					},
					"HEXDIG": {
						PackagePath: "github.com/ghettovoice/abnf/pkg/abnf_core",
						PackageName: "abnf_core",
						IsOperator:  true,
					},
					"DQUOTE": {
						PackagePath: "github.com/ghettovoice/abnf/pkg/abnf_core",
						PackageName: "abnf_core",
						IsOperator:  true,
					},
					"ALPHA": {
						PackagePath: "github.com/ghettovoice/abnf/pkg/abnf_core",
						PackageName: "abnf_core",
						IsOperator:  true,
					},
				},
			},
		),
	)
})

func TestCodeGenerator_ReservedWords(t *testing.T) {
	RegisterTestingT(t)

	src := []byte(
		"var = type / struct\n" +
			"type = \"0\" / \"1\"\n" +
			"struct = %x41-5A / %x61-7A\n",
	)
	g := &abnf_gen.CodeGenerator{
		PackageName: "reserved_words",
		AsOperators: true,
	}
	if _, err := g.ReadFrom(bytes.NewReader(src)); err != nil {
		t.Fatal(err)
	}

	var dst bytes.Buffer
	if _, err := g.WriteTo(&dst); err != nil {
		t.Fatal(err)
	}

	want := `// This file is generated by abnf - DO NOT EDIT.

package reserved_words

import "github.com/ghettovoice/abnf"

var struct_ abnf.Operator

// Struct rule: struct = %x41-5A / %x61-7A
func Struct(s []byte, ns abnf.Nodes) abnf.Nodes {
	if struct_ == nil {
		struct_ = abnf.Alt(
			"struct",
			abnf.Range("%x41-5A", []byte{65}, []byte{90}),
			abnf.Range("%x61-7A", []byte{97}, []byte{122}),
		)
	}
	return struct_(s, ns)
}

var type_ abnf.Operator

// Type rule: type = "0" / "1"
func Type(s []byte, ns abnf.Nodes) abnf.Nodes {
	if type_ == nil {
		type_ = abnf.Alt(
			"type",
			abnf.Literal("\"0\"", []byte{48}),
			abnf.Literal("\"1\"", []byte{49}),
		)
	}
	return type_(s, ns)
}

var var_ abnf.Operator

// Var rule: var = type / struct
func Var(s []byte, ns abnf.Nodes) abnf.Nodes {
	if var_ == nil {
		var_ = abnf.Alt(
			"var",
			Type,
			Struct,
		)
	}
	return var_(s, ns)
}
`
	Expect(dst.String()).Should(Equal(want))
}
