name: Run package tests
on:
    workflow_dispatch:
    push:
        branches:
            - master
            - dev
    pull_request:
        branches:
            - master
            - dev
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.19

            - name: Set up project
              run: make setup

            - name: Test
              run: make test

            - name: Send coverage
              env:
                  COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  go install github.com/mattn/goveralls@latest
                  goveralls -coverprofile=./cover.profile -service=github
